name: Validate pull requests
on:
    pull_request:

concurrency:
    group: ${{ github.ref }}
    cancel-in-progress: true

permissions:
    # This is needed for terraform action to write comments on a PR
    pull-requests: write

jobs:
    scan-for-secrets:
        name: Scan for Secrets
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
            with:
              fetch-depth: 0
          - uses: gitleaks/gitleaks-action@v2
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}}